# Generated by Django 4.2.1 on 2023-05-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('beauty', 'beauty'), ('fashion', 'fashion'), ('food', 'food'), ('lifestyle', 'lifestyle')], max_length=150)),
                ('pic', models.FileField(default='ladki.jpeg', upload_to='blog_photos')),
            ],
        ),
    ]
